Procedure.create(:name => "Coronary Angiography", :abbrev => "C/A", :options => "Setup only, Inject, Non-Inject")
Procedure.create(:name => "Percutaneious Coronary Intervention", :abbrev => "PCI", :options => "Setup only, Inject, Non-Inject")
Procedure.create(:name => "Percutaneous transluminal coronay angioplasty", :abbrev => "PTCA", :options => "Setup only, Inject, Non-Inject")
Procedure.create(:name => "Plain old balloon angioplasty", :abbrev => "POBA", :options => "Setup only, Inject, Non-Inject")
Procedure.create(:name => "Permanent Pacemaker", :abbrev => "PPM", :options => "Setup only, Assist with Procedure")
Procedure.create(:name => "Rotablator", :abbrev => "ROTA", :options => "")
Procedure.create(:name => "Fractional Flow Reserve", :abbrev => "FFR", :options => "")
Procedure.create(:name => "Intravascular Ultrasound", :abbrev => "IVUS", :options => "")
Procedure.create(:name => "Optimal Computer Tomography", :abbrev => "OCT", :options => "")
Procedure.create(:name => "Fliterwire", :abbrev => "FILTER", :options => "")
Procedure.create(:name => "Thrombectomy Device", :abbrev => "", :options => "")
Procedure.create(:name => "Intra-Aotic Balloon Pump", :abbrev => "IABP", :options => "")
Procedure.create(:name => "Pericardiocentesis", :abbrev => "", :options => "")
Procedure.create(:name => "Bi-Ventricular Pacemaker", :abbrev => "BI V", :options => "")
Procedure.create(:name => "Automatic Internal Cardiac Defibrillator", :abbrev => "AICD, ICD", :options => "")
Procedure.create(:name => "Femoral Sheath Removal", :abbrev => "", :options => "")
Procedure.create(:name => "Radial Sheath Removal", :abbrev => "", :options => "")
Procedure.create(:name => "Vascular Closure device", :abbrev => "VCD", :options => "")
Procedure.create(:name => "Renal Denervation", :abbrev => "", :options => "")
Procedure.create(:name => "Percutaneous Core Valve", :abbrev => "", :options => "")
Procedure.create(:name => "Trans-Aortic Valve Implantation", :abbrev => "TAVI", :options => "")
Procedure.create(:name => "Mitral Clip", :abbrev => "", :options => "")
Procedure.create(:name => "Septal Puncture", :abbrev => "", :options => "")
Procedure.create(:name => "Structural Heart - Patent Foramen Ovale", :abbrev => "PFO", :options => "")
Procedure.create(:name => "Structural Heart - Patent Ductus Arteriosus", :abbrev => "PDA", :options => "")
Procedure.create(:name => "Structural Heart - Atrial Septal Defect", :abbrev => "ASD", :options => "")
Procedure.create(:name => "Structural Heart - Left Atrial Appendage", :abbrev => "LAA", :options => "")
Procedure.create(:name => "Valvuloplasty", :abbrev => "", :options => "Mitral, Aortic, Pulmonary, Tricuspid")
Procedure.create(:name => "Exercise Stress Test", :abbrev => "", :options => "")
Procedure.create(:name => "Dobutamine Stress Echo", :abbrev => "DSE", :options => "")
Procedure.create(:name => "Transoesophageal Echogardiography", :abbrev => "TOE", :options => "Bubble Study?")
Procedure.create(:name => "Elective DCR", :abbrev => "", :options => "")
Procedure.create(:name => "Temporary  Pacing Wire ", :abbrev => "Temp wire", :options => "")
Procedure.create(:name => "Emergency Intubation", :abbrev => "", :options => "")
Procedure.create(:name => "Covered Stent", :abbrev => "", :options => "")
Procedure.create(:name => "Advanced Life Support", :abbrev => "ALS", :options => "")
Procedure.create(:name => "Basic Life  Support", :abbrev => "BLS", :options => "")
Procedure.create(:name => "Intra venous Cannulation", :abbrev => "IVC", :options => "")
Procedure.create(:name => "Intra venous Therapy", :abbrev => "IVT", :options => "")
Procedure.create(:name => "Ventricular assist device", :abbrev => "VAD", :options => "")
Procedure.create(:name => "Interventional Nurses Council", :abbrev => "INC", :options => "")
Procedure.create(:name => "Femostop device", :abbrev => "Fem stop", :options => "")
