Procedure.create(:name => "Coronary Angiography", :abbrev => "C/A", :options => "Laser?")
Procedure.create(:name => "Percutaneious Coronary Intervention", :abbrev => "PCI", :options => "")
Procedure.create(:name => "C/A + PCI", :abbrev => "", :options => "alpha team,buttcake,simpletoon,monkey want bannanas")
Procedure.create(:name => "Permanent Pacemaker", :abbrev => "PPM", :options => "")
Procedure.create(:name => "Temporary Pacemaker", :abbrev => "TEMP WIRE", :options => "")
Procedure.create(:name => "Rotablator", :abbrev => "ROTA", :options => "")
Procedure.create(:name => "Fractional Flow Reserve", :abbrev => "FFR", :options => "")
Procedure.create(:name => "Intravascular Ultrasound", :abbrev => "IVUS", :options => "")
Procedure.create(:name => "Optimal Computer Tomography", :abbrev => "OCT", :options => "")
Procedure.create(:name => "Fliterwire", :abbrev => "FILTER", :options => "")
Procedure.create(:name => "Thrombectomy Device", :abbrev => "", :options => "")
Procedure.create(:name => "Intra-Aotic Balloon Pump", :abbrev => "IABP", :options => "")
Procedure.create(:name => "Pericardiocentesis", :abbrev => "", :options => "")
Procedure.create(:name => "Bi-Ventricular Pacemaker", :abbrev => "BI V", :options => "")
Procedure.create(:name => "Automatic Internal Cardiac Defibrillator", :abbrev => "AICD, ICD", :options => "")
Procedure.create(:name => "Femoral Sheath Removal", :abbrev => "", :options => "")
Procedure.create(:name => "Radial Sheath Removal", :abbrev => "", :options => "")
Procedure.create(:name => "Renal Denervation", :abbrev => "", :options => "")
Procedure.create(:name => "Percutaneous Core Valve", :abbrev => "", :options => "")
Procedure.create(:name => "Trans-Aortic Valve Implantation", :abbrev => "TAVI", :options => "")
Procedure.create(:name => "Mitral Clip", :abbrev => "", :options => "")
Procedure.create(:name => "Septal Puncture", :abbrev => "", :options => "")
Procedure.create(:name => "Structaul Heart", :abbrev => "", :options => "PFO (Patent Foramen Ovale), PDA (Patent Ductus Arteriosus),ASD (Atrial Septal Defect),LAA (Left Atrial Appendage)")
Procedure.create(:name => "Valvuloplasty", :abbrev => "", :options => "Mitral, Aortic, Pulmonary, Tricuspid")
Procedure.create(:name => "Exercise Stress Test", :abbrev => "", :options => "")
Procedure.create(:name => "Dobutamine Stress Echo", :abbrev => "", :options => "")
Procedure.create(:name => "Elective Dcr", :abbrev => "", :options => "")
Procedure.create(:name => "Transoesophageal Echogardiography", :abbrev => "TOE", :options => "")
Procedure.create(:name => "IAPB", :abbrev => "", :options => "")
Procedure.create(:name => "Pericardialcenteses", :abbrev => "", :options => "Canine?")
Procedure.create(:name => "Temp Pacing Wire", :abbrev => "", :options => "")
Procedure.create(:name => "Emergency Intubation", :abbrev => "", :options => "")
Procedure.create(:name => "Covered Stent", :abbrev => "", :options => "")
Procedure.create(:name => "Advanced Life Support", :abbrev => "ALS", :options => "")
Procedure.create(:name => "IV Cannulation", :abbrev => "", :options => "")
